project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls"))
]

from django.conf.urls.static import static
from django.conf import settings

url_patterns_for_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + url_patterns_for_media

project/core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import PeliculaCreate, PeliculaList, PeliculaDetail, PeliculaUpdate, PeliculaDelete,registro_view, login_view, editar_perfil_view, crear_avatar_view
from django.contrib.auth.views import LogoutView

app_name = "core"

urlpatterns = [
    path("", views.home, name="index"),
    path("acerca-de-mi/", views.about, name="about"),
    path("lista-peliculas/", PeliculaList.as_view(), name="lista-peliculas"),
    path("detalle-pelicula/<int:pk>/", PeliculaDetail.as_view(), name="detalle-pelicula"),
    path("crear-pelicula/", PeliculaCreate.as_view(), name="crear-pelicula"),
    path("editar-pelicula/<int:pk>/", PeliculaUpdate.as_view(), name="editar-pelicula"),
    path("eliminar-pelicula/<int:pk>/", PeliculaDelete.as_view(), name="eliminar-pelicula"),
    path('detalle-pelicula/<int:pk>/comentar/', views.ComentarioCreate.as_view() , name='comentario'),

    path("registro", registro_view, name="registro"),
    path("login", login_view, name="login"),
    path("logout", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("editar-perfil", editar_perfil_view, name="editar-perfil"),
    path("crear-avatar", crear_avatar_view, name="crear-avatar")
    

]
    
    

project/core/models.py
from django.db import models
from django.contrib.auth.models import User


class Pelicula(models.Model):
    titulo = models.CharField(max_length=100)
    autor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    categoria = models.CharField(max_length=100)
    year = models.IntegerField()
    fechaPublicacion = models.DateTimeField(auto_now_add=True)
    descripcion = models.CharField(max_length=400, default="")
    imagenPortada= models.ImageField(null=True, blank=True, upload_to="imagenes/")

    class Meta:
        ordering = [ '-fechaPublicacion']

    def __str__(self):
        return self.titulo 
    
class Comentario(models.Model):
    comentario = models.ForeignKey(Pelicula, related_name='comentarios', on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    mensaje = models.TextField(null=True, blank=True)
    fechaComentario = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-fechaComentario']

    def __str__(self):
        if self.autor:
            return f'{self.autor.username} - {self.comentario}'
        else:
            return f'None- {self.comentario}'
    
class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(upload_to="media/avatares", null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.imagen}"

project/core/forms.py
from django import forms
from .models import Pelicula, Comentario, Avatar
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UserModel

class PeliculaForm(forms.ModelForm):
    class Meta:
        model = Pelicula
        fields = ('titulo', 'categoria', 'year', 'descripcion', 'imagenPortada' )
        labels = {'year':'Año', 'titulo':'Película'}
        widgets = {
            'descripcion': forms.Textarea(attrs={'rows': 4, 'cols': 20, 'style': 'vertical-align: top'}),}
        
class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('mensaje',)


class EditarPelicula(forms.ModelForm):
    class Meta:
        model = Pelicula
        fields = "__all__"
        labels = {'year':'Año', 'titulo':'Película'}
        widgets = {
            'descripcion': forms.Textarea(attrs={'rows': 4, 'cols': 20, 'style': 'vertical-align: top'}),}
        
class UserCreationForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model = UserModel
        fields = ["username", "email","password1", "password2"]
        help_texts = {k: "" for k in fields}


class UserEditionForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")

    class Meta:
        model = UserModel
        fields = ["email", "password1", "password2", "first_name", "last_name"]
        help_texts = {k: "" for k in fields}


class UserAvatarForm(forms.ModelForm):

    class Meta:
        model = Avatar
        fields = ["imagen"]

project/core/views.py
from django.shortcuts import render, redirect
from .models import Pelicula, Comentario, Avatar
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from .forms import PeliculaForm, ComentarioForm, EditarPelicula, UserCreationForm, UserEditionForm, UserAvatarForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate

# Create your views here.

def home(request):
    if request.user.is_authenticated:
        usuario = request.user
        avatar = Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""

    return render(request, "core/index.html", context={"avatar_url":avatar_url})

def about(request):
    return render(request, "core/acerca_de_mi.html")


class PeliculaList(ListView): 

    model = Pelicula
    template_name = "core/peliculas_list.html"
    context_object_name = "peliculas"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            usuario = self.request.user
            avatar_url = obtener_avatar_url(usuario)
            context['avatar_url'] = avatar_url
        return context

class PeliculaDetail(DetailView):
    model = Pelicula
    template_name = "core/pelicula_detail.html"
    context_object_name = "pelicula"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pelicula = self.get_object()
        comentarios = Comentario.objects.filter(comentario=pelicula)
        print(comentarios)

        context['comentarios'] = comentarios
        return context

    
class PeliculaCreate(CreateView):
    model = Pelicula
    form_class = PeliculaForm
    template_name = "core/pelicula_create.html"
    success_url = reverse_lazy("core:lista-peliculas")
    
    def form_valid(self, form):
        form.instance.autor = self.request.user  # Asignar el usuario actual como autor
        return super().form_valid(form)

    

class PeliculaUpdate(UpdateView):
    model = Pelicula
    template_name = "core/pelicula_update.html"
    form_class = EditarPelicula
    context_object_name = 'editar_pelicula'
    success_url = reverse_lazy("core:lista-peliculas")

class PeliculaDelete(DeleteView):
    model = Pelicula
    template_name = "core/pelicula_delete.html"
    success_url = reverse_lazy("core:lista-peliculas")

class ComentarioCreate( CreateView):
    model = Comentario
    form_class = ComentarioForm
    template_name = 'core/comentario.html'
    success_url = reverse_lazy('core:lista-peliculas')

    def form_valid(self, form):
        form.instance.autor = self.request.user
        form.instance.comentario_id = self.kwargs['pk']
        return super(ComentarioCreate, self).form_valid(form)
    

    




##LOGIN / LOGOUT
def registro_view(request):
    if request.method == "GET":
        return render(request, "core/registro.html", {"form": UserCreationForm()})
    else:
        formulario = UserCreationForm(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            formulario.save()

            return render(
                request,
                "core/index.html",
                {"mensaje": f"Te registraste correctamente, {usuario}!"}
            )
        else:
            return render(
                request,
                "core/registro.html",
                {"form": formulario}
            )

def login_view(request):
    if request.user.is_authenticated:
        return render(
            request,
            "core/index.html",
            {"mensaje": f"Ya estás autenticado: {request.user.username}"}
        )

    if request.method == "GET":
        return render(
            request,
            "core/login.html",
            {"form": AuthenticationForm()}
        )
    else:
        formulario = AuthenticationForm(request, data=request.POST)

        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            password = informacion["password"]

            modelo = authenticate(username=usuario, password=password)
            login(request, modelo)

            return render(
                request,
                "core/index.html",
                {"mensaje": f"Bienvenido {request.user.username}"}
            )
        else:
            return render(
                request,
                "core/login.html",
                {"form": formulario}
            )

@login_required
def editar_perfil_view(request):

    usuario = request.user
    avatar = Avatar.objects.filter(user=usuario).last()
    avatar_url = avatar.imagen.url if avatar is not None else ""


    if request.method == "GET":


        valores_iniciales = {
            "email": usuario.email,
            "first_name": usuario.first_name,
            "last_name": usuario.last_name
        }


        formulario = UserEditionForm(initial=valores_iniciales)
        return render(
            request,
            "core/editar_perfil.html",
            context={"form": formulario, "usuario": usuario, "avatar_url": avatar_url}
            )
    else:
        formulario = UserEditionForm(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario.email = informacion["email"]
            usuario.set_password(informacion["password1"])
            usuario.first_name = informacion["first_name"]
            usuario.last_name = informacion["last_name"]
            usuario.save()
        return redirect("core:index")



def crear_avatar_view(request):

    usuario = request.user

    if request.method == "GET":
        formulario = UserAvatarForm()
        return render(
            request,
            "core/crear_avatar.html",
            context={"form": formulario, "usuario": usuario}
        )
    else:
        formulario = UserAvatarForm(request.POST, request.FILES)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            modelo = Avatar(user=usuario, imagen=informacion["imagen"])
            modelo.save()
            return redirect("core:index")


def obtener_avatar_url(usuario):
    avatar = Avatar.objects.filter(user=usuario).last()
    return avatar.imagen.url if avatar is not None else ""    

project/core/templates/core/acerca_de_mi.html
{% extends 'core/base.html' %}

{% load static %}

{% block contenido %}
    <!-- Estilos para el contenido -->
    <style>
        .about-content {
            font-family: Arial, sans-serif;
            color: #4a90e2;
            max-width: 600px;
            margin: auto;
            padding: 20px;
            text-align: center;
        }

        .about-content img {
            max-width: 200px; /* Cambia el tamaño según tu preferencia */
            height: auto;
            margin-bottom: 20px;
            border-radius: 50%; /* Hace que la imagen sea redonda */
            border: 3px solid #4a90e2; /* Borde alrededor de la imagen */
            display: block;
            margin: 0 auto; /* Centra la imagen */
        }
    </style>

    <!-- Contenido específico de la página "Acerca de mí" -->
    <div class="about-content">
        <h2>Constanza Ojeda</h2>
        <img src="{% static 'core/images/foto_mia.jpg' %}" alt="Mi Imagen">
        <p>Que tal! mi nombre es Constanza, me dicen Coni. Trabajo en el rubro de la estética (¡Nada que ver!) y esta es mi primera vez desarrollando un proyecto. Antes estudié un poco de HTML y CSS, con eso me di cuenta de que quería adentrarme más en este mundo de lo que es la programación y aca estoy!... Aprendí muchísimo de este nuevo lenguaje.Gracias por visitar mi página!
        </p>
    </div>
{% endblock %}

project/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CineSpeak</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        <!-- Navigation-->
        {% include 'core/navbar.html' %}

        {% block titulo %}
            
        {% endblock titulo %}

        {% block contenido %}
            
        {% endblock contenido %}
       
  

        <!-- Section-->
        
        <!-- Footer-->
       {% include 'core/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/crear_avatar.html
{% extends 'core/base.html' %}

{% block contenido %}
<!DOCTYPE html>
 <html lang="en">

 <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4; max-width: 600px; margin: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">

    <h6 style="color: #4a90e2; border-bottom: 2px solid #4a90e2; padding-bottom: 10px;">
        Crear avatar para: {{ usuario }}
    </h6>

    <div style="margin-top: 20px; background-color: white; padding: 20px; border-radius: 5px;">
        <form action="{% url 'core:crear-avatar' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Guardar" style="background-color: #4a90e2; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">
        </form>

    </div>

</div>
{% endblock%}

project/core/templates/core/footer.html
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Proyecto creado en 2023</p></div>
</footer>

project/core/templates/core/header.html
<br>
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            {% if user.is_authenticated %}
                <h1 class="display-4 fw-bolder">Bienvenido(a), {{ user.username }}</h1>
                <p class="lead fw-normal text-white-50 mb-0">Forjamos una comunidad sobre cine</p>
                <br>
                <a href="{% url 'core:lista-peliculas' %}"class="btn btn-primary">Ver foro</a>
            {% else %}
                <h1 class="display-4 fw-bolder">Bienvenido</h1>
                <p class="lead fw-normal text-white-50 mb-0">Forjamos una comunidad sobre cine</p>
                <p class="lead fw-normal text-white-50 mb-0">Inicia sesión o regístrate para acceder a nuestro foro</p>
            {% endif %}
           
            
            
        </div>
    </div>
</header>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    
{% endblock titulo %}

{% block contenido %}

{{mensaje}}
    <!-- Header-->
    {% include 'core/header.html' %}

    <!-- Content-->
   <br>
   <br>
    

{% endblock contenido %}

project/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block contenido%}
<h2>Has cerrado sesión</h2>
{% endblock%}

project/core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="#!">CineSpeak</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:lista-peliculas' %}">Foro</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">Acerca de Mi</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:editar-perfil' %}">EditarPerfil</a></li>
                    <li class="nav-item">
                        <img src="{{ avatar_url }}" style="height: 40px; width: auto; border-radius: 50%; vertical-align: middle;"/>
                    </li>
                    <form action="{% url 'core:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="nav-link" style="background: none; border: none; cursor: pointer;">Cerrar sesión</button>
                    </form>
        {% else %}
            <a class="navbar-brand" href="{% url 'core:login' %}">Iniciar Sesión</a>
            <a class="navbar-brand" href="{% url 'core:registro' %}">Registrarme</a>
        {% endif %}
        
              

        
        </div>
    </div>
</nav>

project/core/templates/core/pelicula_create.html
{% extends 'core/base.html' %}

{% block contenido %}

<style>
    .form-container {
        background-color: white;
        padding: 40px;
        border-radius: 15px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        width: 50%;
        margin: 50px auto;
        text-align: center;
    }

    .form-container h2 {
        margin-bottom: 20px;
        color: rgb(26, 95, 117);
    }

    .form-field {
        margin-bottom: 15px;
    }

    input[type="submit"] {
        background-color: rgb(26, 95, 117);
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
    }
</style>

<div class="form-container">
    <h2>Agregar Posteo</h2>
    <form action="{% url 'core:crear-pelicula' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-field">
            {{ form.as_p }}
        </div>
        <input type="submit" value="Publicar">
    </form>
</div>

{% endblock%}

project/core/templates/core/pelicula_delete.html
{% extends "core/base.html" %}

{% block contenido %}

<style>
    .centered-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        height: 100vh;
    }

    .warning-message {
        background-color: #ffcccb;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        text-align: center;
        margin-bottom: 20px;
    }

    .warning-message h1 {
        color: red;
    }

    .warning-message p {
        font-size: 18px;
    }

    .submit-button {
        background-color: red;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
    }
</style>

<div class="centered-container">
   
    <div class="warning-message">
        <h1>Borrar Posteo: {{pelicula.titulo}}</h1>
        <p>¿Estás seguro que deseas borrar tu publicación: <strong>{{pelicula.titulo}}?</strong> </p>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Eliminar" class="submit-button">
    </form>
</div>

{% endblock %}

project/core/templates/core/pelicula_detail.html
{{% extends 'core/base.html' %}

{% block contenido %}

<div class="container">


<p><h4>{{pelicula.titulo}}</h4></p>
<p><img src="{{pelicula.imagenPortada.url}}" alt=""  class="col-md-3 mb-4"></p>
<p>Titulo: {{pelicula.titulo}}</p>
<p>Categoría: {{pelicula.categoria}}</p>
<p>Estreno: {{pelicula.year}}</p>
<p>Reseña: {{pelicula.descripcion}}</p>
<p><small>{{ pelicula.fechaPublicacion }}</small></p>
}
</div>
<br>
<div class="container">
    <h4>Comentarios</h4>
    <br>
    {% if comentarios %}
        {% for comentario in comentarios %}
            <p><strong>{{comentario.autor}}</strong></p>
            <p>{{ comentario.mensaje }}</p>
            <p><small>{{ comentario.fechaComentario }}</small></p>
            <hr>
        {% endfor %}
    {% else %}
        <p>No hay comentarios</p>
    {% endif %}
    <br>
    <a href="{% url 'core:comentario' pelicula.pk %}" class="btn btn-primary">Agregar un Comentario</a>
    </div>
</div>
<br>
{% endblock %}

project/core/templates/core/pelicula_update.html
{% extends 'core/base.html' %}

{% block contenido %}

<style>
    .form-container {
        background-color: white;
        padding: 40px;
        border-radius: 15px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        width: 50%;
        margin: 50px auto;
        text-align: center;
    }

    .form-container h2 {
        margin-bottom: 20px;
        color:#24b1ca;
    }

    .form-field {
        margin-bottom: 15px;
    }

    input[type="submit"] {
        background-color: #24b1ca;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 8px;
    }
</style>

<div class="form-container">
    <h2>Editar Posteo</h2>
    <form action="{% url 'core:editar-pelicula' editar_pelicula.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-field">
            {{ form.as_p }}
        </div>
        <input type="submit" value="Editar">
    </form>
</div>

    
{% endblock contenido %}

project/core/templates/core/peliculas_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}

<a href="{% url 'core:crear-pelicula'%}" class="btn btn-primary">Publicar</a>
<br>
<br>

<div class="row">
    {% if peliculas %}
        {% for pelicula in peliculas %}
            <div class="col-md-2 mb-3">
                <div class="card">
                    <img src="{{ pelicula.imagenPortada.url }}" class="card-img-top" alt="{{ pelicula.titulo }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ pelicula.titulo }}</h5>
                        <p class="card-text"><strong>Por:</strong> {{ pelicula.autor }}</p>
                        <p class="card-text"><strong>Categoría:</strong> {{ pelicula.categoria }}</p>
                        <a href="{% url 'core:detalle-pelicula' pelicula.id %}" class="btn btn-primary">Ver Detalles</a>
                        <br>
                        {% if user.id == pelicula.autor.id %}
                        
                        <a href="{% url 'core:eliminar-pelicula' pelicula.id %}" class="btn btn-danger">Eliminar</a>
                        <a href="{% url 'core:editar-pelicula' pelicula.id %}" class="btn btn-secondary">Editar</a>
                            
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>No existen películas en la base de datos.</h3>
    {% endif %}
</div>
    
{% endblock contenido %}

project/core/templates/core/registro.html
{% extends 'core/base.html' %}

{% block contenido %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <style>
        body {
            background-color: rgb(227, 224, 225);
            font-family: Arial, sans-serif;
        }
        .form-container {
            padding: 20px;
            background-color: #f4f4f4;
            max-width: 600px;
            margin: auto;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        h2 {
            color: #4a90e2;
            border-bottom: 2px solid #4a90e2;
            padding-bottom: 10px;
        }
        .form-content {
            margin-top: 20px;
            background-color: white;
            padding: 20px;
            border-radius: 5px;
        }
        .form-field {
            display: block;
            margin-bottom: 10px;
        }
        .form-label {
            color: #4a90e2;
            margin-bottom: 5px;
        }
        .form-input {
            width: 100%;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        .submit-button {
            background-color: #4a90e2;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .error-list {
            color: red;
        }
    </style>
</head>

<body>
    <div class="form-container">
        <h2>Registro</h2>
        <div class="form-content">
            <form action="{% url 'core:registro' %}" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    <input class="form-input" type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" value="{{ field.value|default_if_none:'' }}" {% if field.field.required %}required{% endif %}>
                    {% if field.errors %}
                        <ul class="error-list">
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endfor %}
                <input class="submit-button" type="submit" value="Registrarme">
            </form>
        </div>
    </div>
</body>
</html>
{% endblock %}